const actions = {
  GET_PEMINJAM: "GET_PEMINJAM",
  GET_NAMA_PETUGAS: "GET_NAMA_PETUGAS",
  GET_NAMA_ANGGOTA: "GET_NAMA_ANGGOTA",
  GET_ANGGOTA: "GET_ANGGOTA",
  ADD_ANGGOTA: "ADD_ANGGOTA",
  EDIT_ANGGOTA: "EDIT_ANGGOTA",
  DELETE_ANGGOTA: "DELETE_ANGGOTA",
  GET_PETUGAS: "GET_PETUGAS",
  SET_LOADING: "SET_LOADING",
  GET_BUKU: "GET_BUKU",
  ADD_BUKU: "ADD_BUKU",
  EDIT_BUKU: "EDIT_BUKU",
  DELETE_BUKU: "DELETE_BUKU"
};

export default actions;
